### ISSUE TITLE
Build is broken on the current repo

### ISSUE THREAD

**Issue by garylinscott** [google-deepmind/reverb#143]
Hi, it appears some internal Google paths/checks have made it into the repo, and it now doesn't build.  https://github.com/garylinscott/reverb/pull/1 fixes this, and gets a build against TF 2.15.1 (which is nice as it's cuda 12).  I haven't tried newer TF versions yet though.

**Comment by GoingMyWay** [comment]
@garylinscott I am using your PR to build the whl file but got the following error:

```bash
bazel build -c opt //reverb/pip_package:build_pip_package
INFO: Analyzed target //reverb/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/fe52dc3c7bd9920361c3fd1525565fb2/external/boringssl/BUILD:161:11: Compiling src/crypto/x509v3/v3_utl.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 41 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/boringssl/src/crypto/x509v3/v3_utl.c:1190:37: error: argument 1 of type 'unsigned char *' declared as a pointer [-Werror=array-parameter=]
 1190 | int x509v3_a2i_ipadd(unsigned char *ipout, const char *ipasc)
      |                      ~~~~~~~~~~~~~~~^~~~~
In file included from external/boringssl/src/crypto/x509v3/v3_utl.c:74:
external/boringssl/src/crypto/x509v3/internal.h:61:36: note: previously declared as an array 'unsigned char[16]'
   61 | int x509v3_a2i_ipadd(unsigned char ipout[16], const char *ipasc);
      |                      ~~~~~~~~~~~~~~^~~~~~~~~
cc1: all warnings being treated as errors
Target //reverb/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 64.985s, Critical Path: 19.75s
INFO: 355 processes: 10 internal, 345 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

Any hint to fix the issue?

**Comment by GoingMyWay** [comment]
I tried to add the following to .bazelrc

```
build --copt=-Wno-array-parameter
build --copt=-Wno-error=array-parameter
```

I got the whl file but importing reverb fail:

```
>>> import reverb\2025-03-29 20:47:54.968517: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.2025-03-29 20:47:55.016396: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered2025-03-29 20:47:55.016428: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered2025-03-29 20:47:55.017964: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered2025-03-29 20:47:55.025473: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "<stdin>", line 1, in <module>  File "/tmp/reverb/reverb/__init__.py", line 27, in <module>    from reverb import item_selectors as selectors  File "/tmp/reverb/reverb/item_selectors.py", line 19, in <module>    from reverb import pybindImportError: cannot import name 'pybind' from partially initialized module 'reverb' (most likely due to a circular import) (/tmp/reverb/reverb/__init__.py)
```
